### ISSUE TITLE
All products view

### ISSUE THREAD

**Issue by alliefrench** [grace-shopper-afksezdm/stackshop#2]
Story: As a user/guest, I want to view a list of available products so that I can choose to view a product in more detail.

Implementation: Create home page with nav bar linking to all products view. All our products should display on that view, giving the user the ability to link to a single product view for more information.

- [x] Define Postgres database for our website #9  
- [x]  Create Product model to hold name, description, cost and image. Add validations to ensure proper data types. #9 
- [x] Write express route to serve up all product information #8 
- [ ] Create React component that will render a nav bar. It should contain buttons linking to all products, login, sign up and cart #7 
- [ ] Create React component that will render a single product link and thumbnail picture #6 
- [ ] Create a React component that will render all products together #
- [ ] Create a Redux store that will make an axios request to our all products GET route and set them as 'all products' in state #5
